import type { Page } from "@playwright/test";
import { hostFixture } from "./host-fixture";

export const model = "fixture-model:small";
type Channel = "local" | "internet";
type Internet = {
  state: "off" | "starting" | "verifying" | "live" | "interrupted" | "stopping" | "failed";
  provider: "cloudflare-quick";
  available: boolean;
  publicUrl: string | null;
  checkedAt: string | null;
  error: string | null;
  restartRequired?: boolean;
};
export type SharingTestWindow = typeof window & {
  sharingCopies: string[];
  sharingCopyFails?: boolean;
};
export const publicOrigin = "https://temporary-fixture.trycloudflare.com";
/**
 * The only secret this fixture ever mints. Any appearance of it outside a reveal the host
 * explicitly asked for is a leak, so specs search for this exact string.
 */
export const secret = "fixture-secret";
export const grant = (channel?: Channel) => ({
  id: "b475df22-52e7-4f2d-89f2-b7b655cae056",
  label: "Visitor",
  model,
  createdAt: new Date().toISOString(),
  expiresAt: new Date(Date.now() + 3600000).toISOString(),
  revokedAt: null as string | null,
  channel,
  recoverable: true,
});
/**
 * A key approved from a guest request: the guest derived the secret itself, so the gateway
 * stores no copy and can never reissue it.
 */
export const derivedGrant = () => ({
  ...grant("internet"),
  id: "0c9a1f6e-6a2b-4a54-9a2c-2f7dd2a80c11",
  label: "Approved guest",
  recoverable: false,
});
/** The durable key the gateway hands back: version, grant id, then the secret. */
export const keyToken = (id: string = grant().id) => `hga1.${id}.${secret}`;
export async function accessFixture(page: Page, names = [model]) {
  await hostFixture(page, true, names);
  await page.addInitScript(() => {
    (window as SharingTestWindow).sharingCopies = [];
    Object.defineProperty(navigator, "clipboard", {
      value: {
        writeText: async (text: string) => {
          if ((window as SharingTestWindow).sharingCopyFails)
            throw new DOMException("Clipboard blocked", "NotAllowedError");
          (window as SharingTestWindow).sharingCopies.push(text);
        },
      },
    });
  });
  const state = {
    state: "stopped",
    hostLabel: "Local host",
    model: null as string | null,
    guestUrl: null as string | null,
    error: null as string | null,
    grants: [] as ReturnType<typeof grant>[],
    removableKeys: undefined as number | undefined,
    internet: {
      state: "off",
      provider: "cloudflare-quick",
      available: true,
      publicUrl: null,
      checkedAt: null,
      error: null,
    } as Internet | undefined,
  };
  const calls: string[] = [];
  const bodies: {
    channel?: Channel;
    label?: string;
    expiresInHours?: number;
    model?: string;
    hostLabel?: string;
  }[] = [];
  const cleanup = { enabled: false, loseResponse: false, wait: null as Promise<void> | null };
  const ended = (key: ReturnType<typeof grant>) =>
    !!key.revokedAt || Date.parse(key.expiresAt) <= Date.now();
  let reads = 0;
  let failRead = false;
  const response = {
    channel: undefined as Channel | undefined,
    /** Overrides the token returned by key creation and by key lookup. */
    token: undefined as string | undefined,
  };
  await page.route("**/api/sharing**", async (route) => {
    const path = new URL(route.request().url()).pathname;
    if (route.request().method() === "GET") {
      reads++;
      if (cleanup.enabled) state.removableKeys = state.grants.filter(ended).length;
      return route.fulfill({
        status: failRead ? 503 : 200,
        json: failRead ? { detail: "The gateway is unavailable." } : state,
      });
    }
    calls.push(path);
    bodies.push(route.request().postDataJSON());
    if (path === "/api/sharing/grants/cleanup") {
      if (!cleanup.enabled)
        return route.fulfill({ status: 404, json: { detail: "Endpoint not found." } });
      const removedCount = state.grants.filter(ended).length;
      state.grants = state.grants.filter((key) => !ended(key));
      state.removableKeys = 0;
      if (cleanup.wait) await cleanup.wait;
      if (cleanup.loseResponse) return route.abort("failed");
      return route.fulfill({ json: { status: state, removedCount } });
    }
    const lookup = /^\/api\/sharing\/grants\/([^/]+)\/key$/.exec(path);
    if (lookup) {
      const key = state.grants.find((item) => item.id === lookup[1] && !ended(item));
      if (!key)
        return route.fulfill({
          status: 404,
          json: { detail: "That key is no longer available." },
        });
      if (!key.recoverable)
        return route.fulfill({
          status: 409,
          json: { detail: "That key was generated by the guest and cannot be reissued." },
        });
      return route.fulfill({ json: { token: response.token ?? keyToken(key.id) } });
    }
    const revoke = /^\/api\/sharing\/grants\/([^/]+)\/revoke$/.exec(path);
    if (revoke) {
      const key = state.grants.find((item) => item.id === revoke[1]);
      if (key) key.revokedAt = new Date().toISOString();
    } else if (path === "/api/sharing/internet/start") {
      if (state.state !== "local" || !state.internet?.available)
        return route.fulfill({ status: 409, json: { detail: "Internet sharing is unavailable." } });
      Object.assign(state.internet, {
        state: "starting",
        publicUrl: null,
        checkedAt: null,
        error: null,
      });
    } else if (path === "/api/sharing/internet/stop") {
      Object.assign(state.internet!, { state: "stopping", publicUrl: null });
    } else if (path === "/api/sharing/start") {
      const body = route.request().postDataJSON();
      Object.assign(state, body, {
        hostLabel: body.hostLabel.trim(),
        state: "local",
        guestUrl: "http://127.0.0.1:8081",
      });
    } else if (path === "/api/sharing/stop") {
      state.state = "stopped";
      if (state.internet) Object.assign(state.internet, { state: "off", publicUrl: null });
    } else if (path === "/api/sharing/grants") {
      const body = route.request().postDataJSON();
      // Keys are stored by the gateway, so only serving a model gates their creation.
      if (state.state !== "local")
        return route.fulfill({ status: 409, json: { detail: "Guest access is not running." } });
      const item = { ...grant(response.channel ?? body.channel), label: body.label };
      state.grants.push(item);
      return route.fulfill({
        json: { grant: item, token: response.token ?? keyToken(item.id) },
      });
    }
    return route.fulfill({ json: state });
  });
  return {
    state,
    calls,
    bodies,
    response,
    cleanup,
    reads: () => reads,
    failRead: () => {
      failRead = true;
    },
    recoverRead: () => {
      failRead = false;
    },
  };
}

export function publishLocal(fixture: Awaited<ReturnType<typeof accessFixture>>) {
  Object.assign(fixture.state, { state: "local", model, guestUrl: "http://127.0.0.1:8081" });
}

export function publishInternet(fixture: Awaited<ReturnType<typeof accessFixture>>) {
  publishLocal(fixture);
  Object.assign(fixture.state.internet!, {
    state: "live",
    publicUrl: publicOrigin,
    checkedAt: new Date().toISOString(),
  });
}
